# Generated by Django 5.2.17 on 2026-08-13 18:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(default='Guest', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('local', 'Pass & Play'), ('online', 'Private Lobby'), ('ranked', 'Ranked')], default='local', max_length=8)),
                ('status', models.CharField(choices=[('lobby_waiting', 'Waiting for players'), ('in_progress', 'In progress'), ('complete', 'Complete'), ('abandoned', 'Abandoned')], default='complete', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_created', to='core.guestprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=32)),
                ('seat_order', models.PositiveSmallIntegerField()),
                ('ones', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('twos', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('threes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fours', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fives', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sixes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('three_kind', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('four_kind', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('full_house', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('small_straight', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('large_straight', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('yahtzee', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('chance', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('yahtzee_bonus_count', models.PositiveSmallIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='core.gamesession')),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_played', to='core.guestprofile')),
            ],
            options={
                'ordering': ['seat_order'],
                'unique_together': {('session', 'seat_order')},
            },
        ),
    ]
