# Generated by Django 5.2.17 on 2026-08-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='disconnected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='is_connected',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='active_seat',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='dice',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='held',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='last_scored',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='max_players',
            field=models.PositiveSmallIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='phase',
            field=models.CharField(choices=[('lobby_waiting', 'Waiting for players'), ('selecting_keep', 'Selecting keep'), ('intermission', 'Intermission'), ('game_over', 'Game over')], default='lobby_waiting', max_length=16),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='roll_number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='room_code',
            field=models.CharField(blank=True, db_index=True, max_length=6, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='turn_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='turn_timer_seconds',
            field=models.PositiveSmallIntegerField(default=30),
        ),
    ]
