# Generated by Django 5.2.17 on 2026-08-14 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_gameplayer_disconnected_at_gameplayer_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankedStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elo_rating', models.IntegerField(default=1200)),
                ('games_played', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ranked_stats', to='core.guestprofile')),
            ],
        ),
    ]
